In [1]:
import numpy as np

In [2]:
mat = np.random.randint(0, 10, size=(8, 10))
mat

array([[5, 5, 7, 5, 6, 8, 3, 6, 3, 2],
       [7, 1, 9, 4, 1, 2, 4, 4, 0, 1],
       [4, 7, 8, 3, 4, 5, 4, 0, 1, 1],
       [9, 2, 6, 5, 3, 7, 6, 9, 3, 3],
       [8, 7, 3, 0, 6, 3, 1, 2, 1, 5],
       [1, 8, 9, 8, 1, 3, 1, 3, 9, 3],
       [0, 7, 3, 4, 6, 7, 6, 1, 5, 0],
       [4, 4, 0, 8, 3, 8, 3, 2, 2, 3]])

___

In [6]:
media_col = mat.mean(axis=0)
media_col

array([4.75 , 5.125, 5.625, 4.625, 3.75 , 5.375, 3.5  , 3.375, 3.   ,
       2.25 ])

In [4]:
print(mat.shape, media_col.shape)

(8, 10) (10,)


In [5]:
mat - media_col

array([[ 0.25 , -0.125,  1.375,  0.375,  2.25 ,  2.625, -0.5  ,  2.625,
         0.   , -0.25 ],
       [ 2.25 , -4.125,  3.375, -0.625, -2.75 , -3.375,  0.5  ,  0.625,
        -3.   , -1.25 ],
       [-0.75 ,  1.875,  2.375, -1.625,  0.25 , -0.375,  0.5  , -3.375,
        -2.   , -1.25 ],
       [ 4.25 , -3.125,  0.375,  0.375, -0.75 ,  1.625,  2.5  ,  5.625,
         0.   ,  0.75 ],
       [ 3.25 ,  1.875, -2.625, -4.625,  2.25 , -2.375, -2.5  , -1.375,
        -2.   ,  2.75 ],
       [-3.75 ,  2.875,  3.375,  3.375, -2.75 , -2.375, -2.5  , -0.375,
         6.   ,  0.75 ],
       [-4.75 ,  1.875, -2.625, -0.625,  2.25 ,  1.625,  2.5  , -2.375,
         2.   , -2.25 ],
       [-0.75 , -1.125, -5.625,  3.375, -0.75 ,  2.625, -0.5  , -1.375,
        -1.   ,  0.75 ]])

___

In [8]:
media_row = mat.mean(axis=1)
media_row

array([5. , 3.3, 3.7, 5.3, 3.6, 4.6, 3.9, 3.7])

In [9]:
print(mat.shape, media_row.shape)

(8, 10) (8,)


In [10]:
mat - media_row

ValueError: operands could not be broadcast together with shapes (8,10) (8,) 

In [11]:
print(mat.T.shape, media_row.shape)

(10, 8) (8,)


In [12]:
mat.T - media_row

array([[ 0. ,  3.7,  0.3,  3.7,  4.4, -3.6, -3.9,  0.3],
       [ 0. , -2.3,  3.3, -3.3,  3.4,  3.4,  3.1,  0.3],
       [ 2. ,  5.7,  4.3,  0.7, -0.6,  4.4, -0.9, -3.7],
       [ 0. ,  0.7, -0.7, -0.3, -3.6,  3.4,  0.1,  4.3],
       [ 1. , -2.3,  0.3, -2.3,  2.4, -3.6,  2.1, -0.7],
       [ 3. , -1.3,  1.3,  1.7, -0.6, -1.6,  3.1,  4.3],
       [-2. ,  0.7,  0.3,  0.7, -2.6, -3.6,  2.1, -0.7],
       [ 1. ,  0.7, -3.7,  3.7, -1.6, -1.6, -2.9, -1.7],
       [-2. , -3.3, -2.7, -2.3, -2.6,  4.4,  1.1, -1.7],
       [-3. , -2.3, -2.7, -2.3,  1.4, -1.6, -3.9, -0.7]])

In [14]:
mat

array([[5, 5, 7, 5, 6, 8, 3, 6, 3, 2],
       [7, 1, 9, 4, 1, 2, 4, 4, 0, 1],
       [4, 7, 8, 3, 4, 5, 4, 0, 1, 1],
       [9, 2, 6, 5, 3, 7, 6, 9, 3, 3],
       [8, 7, 3, 0, 6, 3, 1, 2, 1, 5],
       [1, 8, 9, 8, 1, 3, 1, 3, 9, 3],
       [0, 7, 3, 4, 6, 7, 6, 1, 5, 0],
       [4, 4, 0, 8, 3, 8, 3, 2, 2, 3]])

In [13]:
(mat.T - media_row).T

array([[ 0. ,  0. ,  2. ,  0. ,  1. ,  3. , -2. ,  1. , -2. , -3. ],
       [ 3.7, -2.3,  5.7,  0.7, -2.3, -1.3,  0.7,  0.7, -3.3, -2.3],
       [ 0.3,  3.3,  4.3, -0.7,  0.3,  1.3,  0.3, -3.7, -2.7, -2.7],
       [ 3.7, -3.3,  0.7, -0.3, -2.3,  1.7,  0.7,  3.7, -2.3, -2.3],
       [ 4.4,  3.4, -0.6, -3.6,  2.4, -0.6, -2.6, -1.6, -2.6,  1.4],
       [-3.6,  3.4,  4.4,  3.4, -3.6, -1.6, -3.6, -1.6,  4.4, -1.6],
       [-3.9,  3.1, -0.9,  0.1,  2.1,  3.1,  2.1, -2.9,  1.1, -3.9],
       [ 0.3,  0.3, -3.7,  4.3, -0.7,  4.3, -0.7, -1.7, -1.7, -0.7]])

___

In [16]:
media_row.shape

(8,)

In [29]:
media_row = mat.mean(axis=1)

In [30]:
media_row

array([5. , 3.3, 3.7, 5.3, 3.6, 4.6, 3.9, 3.7])

In [25]:
media_row.shape

(8,)

In [31]:
media_row[np.newaxis, :]

array([[5. , 3.3, 3.7, 5.3, 3.6, 4.6, 3.9, 3.7]])

In [26]:
media_row = media_row[:, np.newaxis]

In [27]:
media_row

array([[5. ],
       [3.3],
       [3.7],
       [5.3],
       [3.6],
       [4.6],
       [3.9],
       [3.7]])

In [21]:
media_row

array([[5. ],
       [3.3],
       [3.7],
       [5.3],
       [3.6],
       [4.6],
       [3.9],
       [3.7]])

In [18]:
media_row.shape

(8, 1)

In [19]:
mat.shape

(8, 10)

In [20]:
mat - media_row

array([[ 0. ,  0. ,  2. ,  0. ,  1. ,  3. , -2. ,  1. , -2. , -3. ],
       [ 3.7, -2.3,  5.7,  0.7, -2.3, -1.3,  0.7,  0.7, -3.3, -2.3],
       [ 0.3,  3.3,  4.3, -0.7,  0.3,  1.3,  0.3, -3.7, -2.7, -2.7],
       [ 3.7, -3.3,  0.7, -0.3, -2.3,  1.7,  0.7,  3.7, -2.3, -2.3],
       [ 4.4,  3.4, -0.6, -3.6,  2.4, -0.6, -2.6, -1.6, -2.6,  1.4],
       [-3.6,  3.4,  4.4,  3.4, -3.6, -1.6, -3.6, -1.6,  4.4, -1.6],
       [-3.9,  3.1, -0.9,  0.1,  2.1,  3.1,  2.1, -2.9,  1.1, -3.9],
       [ 0.3,  0.3, -3.7,  4.3, -0.7,  4.3, -0.7, -1.7, -1.7, -0.7]])

___

In [32]:
media_row = mat.mean(axis=1)

print(mat.shape, media_row.shape)

(8, 10) (8,)


In [33]:
media_row = np.expand_dims(media_row, axis=1)

In [34]:
print(mat.shape, media_row.shape)

(8, 10) (8, 1)


In [35]:
mat - media_row

array([[ 0. ,  0. ,  2. ,  0. ,  1. ,  3. , -2. ,  1. , -2. , -3. ],
       [ 3.7, -2.3,  5.7,  0.7, -2.3, -1.3,  0.7,  0.7, -3.3, -2.3],
       [ 0.3,  3.3,  4.3, -0.7,  0.3,  1.3,  0.3, -3.7, -2.7, -2.7],
       [ 3.7, -3.3,  0.7, -0.3, -2.3,  1.7,  0.7,  3.7, -2.3, -2.3],
       [ 4.4,  3.4, -0.6, -3.6,  2.4, -0.6, -2.6, -1.6, -2.6,  1.4],
       [-3.6,  3.4,  4.4,  3.4, -3.6, -1.6, -3.6, -1.6,  4.4, -1.6],
       [-3.9,  3.1, -0.9,  0.1,  2.1,  3.1,  2.1, -2.9,  1.1, -3.9],
       [ 0.3,  0.3, -3.7,  4.3, -0.7,  4.3, -0.7, -1.7, -1.7, -0.7]])

In [36]:
media_row.shape

(8, 1)

In [37]:
media_row.squeeze().shape

(8,)