___
## Módulo 2: Introducción a las librería Numpy.
___

In [2]:
import numpy as np

### 2.1. Introducción a NumPy I.

**2.1.1.**  Crea un vector con valores de 10 a 49 en pasos de 0.5.

In [ ]:
vect = np.arange(10, 49, 0.5)
vect

**2.1.2.** Muestra su dimensión y su tipo.

In [ ]:
vect.shape

In [ ]:
vect.dtype

**2.1.3.** Crea un array con los números que elijas de dimensiones 2x3.

In [ ]:
lista_para_arr = [
    [1,2,3],
    [1,4,2],
]

In [ ]:
np.array(lista_para_arr)

**2.1.4.** Indexing y slicing:

- Crea un array unidimensional de 10 elemento aleatorios.
- Crea un array bidimensional de 10x10 elementos aletorios.
- Accede al primer elemento y al penúltimo número de cada array. 
- Para el array unidimensional: muestra todos los elementos en posiciones pares desde la posición 6. 
- Para el array bidimensional: muestra una submatriz con las dos primeras filas y las tres primeras columnas.
- Divide el array bidimensional en dos: uno con las 2 primera filas y otro con las siguientes

In [ ]:
uni = np.random.rand(10)
bi_dim = np.random.rand(10, 10)

In [ ]:
uni.shape

In [ ]:
bi_dim.shape

In [ ]:
print(uni[0])
print(uni[-2])

In [ ]:
print(bi_dim[0, 0])
print(bi_dim[-2,-2])

In [ ]:
uni[6::2]

In [ ]:
bi_dim[:2,:3]

In [ ]:
vector = np.random.rand(1, 10)

print(vector.shape)
print(vector.T.shape)

In [ ]:
bi_dim_a = bi_dim[:2,:]
bi_dim_b = bi_dim[2:,:]

In [ ]:
bi_dim_a

In [ ]:
bi_dim_b

**2.1.5.** Crea una función que reciba como parámetro un número n y devuelva una matriz cuadrada (dos dimensiones) de nxn donde los elementos de la diagonal principal valgan 5 y el resto valgan n.

In [ ]:
def fun(n):
    return np.eye(n)*5

In [ ]:
fun(3)

**2.1.6.** Crea una función que genere un esquema de tablero de ajedrez (con valores 1 y 0, enteros) en base a dos parámetros: la dimensión (cuadrada) del tablero n y un flag que indique si el primer elemento de la primera fila debe ser un 1 (True) o un 0 (False).

In [ ]:
n = 10

In [ ]:
tablero = np.ones((n, n))
tablero[::2, 1::2] = 0
tablero[1::2, ::2] = 0

In [ ]:
tablero

In [ ]:
tablero = np.ones((n, n))
tablero[::2, ::2] = 0
tablero[1::2,1::2] = 0

In [ ]:
tablero

**2.1.7.** Crea una matriz de números aleatorios de 4*3 (no importa la distribución)

- Localiza con una máscara booleana aquellos números que estén por encima del percentil 90
- Usa la máscara booleana para convertir a 1 aquellos que estén por encima de dicho percentil
- Usa la máscara booleana para convertir a 0 el resto

In [ ]:
matriz = np.random.normal(size=(4, 3))
print(matriz)

limite = np.percentile(matriz, 90)
mascara = matriz > limite

matriz[mascara] = 1
matriz[~mascara] = 0

matriz

**2.1.8.** Crea un vector de números de 1 a 10. 

- Extrae las posiciones 6 a 8 y guárdalas un un nuevo vector
- Iguala el nuevo vector a ceros
- Haz todo lo anterior, de tal forma, que no modifiques el vector original

In [ ]:
original = np.arange(1,11)
print(original)

# copia = original[5:8] # Si lo hacemos así cambiamos ambos vectores
# copia = original[::] # Funciona con listas, pero no funciona con np
copia = original[5:8].copy()
print(copia)

copia[:] = 1
print(copia)
print(original)

**2.1.9.** Genera una matriz de 3x3 de números aleatorios (da igual la distribución)

- Extrae la tercera columna en un vector de 2 dimensiones
- Extrae la tercera columna en un vector de 1 dimensión
- Extrae el segundo y tercer elemento, de la segunda fila, en un vector de 2 dimensiones
- Extrae el segundo y tercer elemento, de la segunda fila, en un vector de 1 dimensión

In [ ]:
matriz = np.random.normal(size=(3, 3))

print(matriz)

ej1 = matriz[0:3, 2:3]
print(ej1.shape)

ej2 = matriz[:,2]
print(ej2.shape)

ej3 = matriz[1:2, 1:]
print(ej3.shape)

ej4 = matriz[1,1:]
print(ej4.shape)

___
### 2.2. Introducción a NumPy II.

**2.2.1.**  Crea una función que reciba dos números n y m que definirán ancho y alto de una matriz de nxm elementos numéricos secuenciales y un booleano que definirá si se debe devolver la matriz generada (False) o su traspuesta (True).

In [ ]:
def mi_fun(n=10, m=10, trp=True):
    mat = np.arange(n*m).reshape((n, m))
    if trp:
        return mat.T
    return mat

In [ ]:
arr = mi_fun(10, 5, True)
arr

**2.2.2.**  Crea una función que reciba una matriz y chequee si hay o no algún valor negativo en la misma.

In [ ]:
def chequear_neg(matriz):
    return (matriz<0).any()

In [ ]:
matriz = np.random.randint(-10, 10, (5,5))
print(matriz)

chequear_neg(matriz)

**2.2.3.** Crea una función que sume el valor absoluto de todos los elementos negativos de una matriz recibida como parámetro. O devuelva "No hay negativos" en caso de que no los haya.

In [ ]:
def suma_val_abs_neg(matriz):
    return np.sum(np.abs(matriz[(matriz<0)]))

In [ ]:
matriz = np.random.randint(-10, 10, (5,5))
print(matriz)

suma_val_abs_neg(matriz)

**2.2.4.** Utiliza el ejercicio 2.1.9. Genera una matriz de 3x3 de números aleatorios (da igual la distribución)

- Extrae la tercera columna en un vector de 2 dimensiones
- Extrae la tercera columna en un vector de 1 dimensión
- Extrae el segundo y tercer elemento, de la segunda fila, en un vector de 2 dimensiones
- Extrae el segundo y tercer elemento, de la segunda fila, en un vector de 1 dimensión

Calcula la traspuesta de los 4 apartados, imprímela y comenta los resultados

In [ ]:
matriz = np.random.normal(size=(3, 3))

print(matriz)

ej1 = matriz[0:3, 2:3]
print(ej1.shape)

ej2 = matriz[:,2]
print(ej2.shape)

ej3 = matriz[1:2, 1:]
print(ej3.shape)

ej4 = matriz[1,1:]
print(ej4.shape)

In [ ]:
print(ej1)
print(ej1.T)
print("")

print(ej2)
print(ej2.T)
print("")

print(ej3)
print(ej3.T)
print("")

print(ej4)
print(ej4.T)

Cuando se trata de un vector, no es columna ni fila. El propio Python lo "coloca" cuando se realiza una multiplicación vector @ matriz. Por esto no se puede calcular la traspuesta. 

___
### 2.3. Introducción a NumPy III.

**2.3.1.** Crea un vector de 30 elementos aleatorios y calcula su media.

In [3]:
vector = np.random.random(30)

In [4]:
np.mean(vector)

0.4762089124894276

In [5]:
vector.mean()

0.4762089124894276

**2.3.2.**Crea una matriz de 8x10 aleatoria y substrae la media por columnas.

In [6]:
matriz = np.random.randint(1, 10, (8,10))
matriz

array([[9, 3, 5, 3, 9, 7, 5, 9, 5, 7],
       [1, 2, 6, 6, 9, 1, 4, 8, 1, 1],
       [1, 9, 8, 4, 8, 9, 5, 3, 9, 8],
       [2, 1, 8, 3, 4, 5, 8, 1, 3, 8],
       [1, 3, 2, 8, 8, 9, 9, 4, 8, 5],
       [1, 2, 8, 9, 8, 9, 4, 6, 8, 6],
       [8, 1, 1, 1, 5, 4, 1, 9, 2, 6],
       [1, 2, 2, 7, 1, 8, 6, 5, 8, 5]])

In [7]:
matriz.shape

(8, 10)

In [13]:
matriz.mean(axis=0)

array([3.   , 2.875, 5.   , 5.125, 6.5  , 6.5  , 5.25 , 5.625, 5.5  ,
       5.75 ])

**2.3.3.** Crea una función que reciba dos enteros n y m, 

- Genere dos matrices aleatorias (normales 0,1) de dimensiones nxm y mxn
- Haga el producto matricial de ambas para obtener una matriz nxn. 

In [14]:
def mxn(a,b):

    x = np.random.rand(a, b)
    y = np.random.rand(b, a)
    
    return np.dot(x,y)

In [15]:
mxn(5,10)

array([[1.81513082, 1.85766995, 1.45510752, 2.03619213, 1.56466396],
       [2.77420835, 2.68796942, 2.12581695, 2.36617271, 1.8047049 ],
       [1.83065919, 2.0085336 , 1.82655089, 2.11626344, 2.21727789],
       [2.51731932, 2.51943186, 1.58716631, 1.8833131 , 1.39616494],
       [2.96169186, 3.03397983, 2.36471108, 2.61491079, 2.13350341]])

**2.3.4.** Crea una función que reciba dos matrices y devuelva la secuencia ordenada, de la unión, de los elementos únicos de ambas.

In [16]:
def func234(matriz1, matriz2):

    np.unique(x)
    np.unique(y)
    inter = np.intersect1d(x,y)
    inter.sort()
    return inter    

In [17]:
x = np.random.randint(1, 10, (2,2))
y = np.random.randint(1, 10, (8,10))

func234(x,y)

array([1, 6, 7])

**2.3.5.** Crea una matriz aleatoria normal de 5x10 y normalízala en media y varianza por columnas (resta la media y divide entre la desviación típica).

- Procedimiento muy típico en ML para normalizar lo que vamos a introducir en la red neuronal

In [32]:
x = np.random.rand(5, 10)

y = x  - x.mean(axis=0)
y = y / x.std(axis=0)
print(y)

[[ 0.36438578 -0.43776253  1.11315043 -1.25131395 -1.04978863 -0.51487912
   0.82481267 -0.71928599 -1.66949253 -0.75889013]
 [-1.12461279  1.90281949 -0.35238371  0.45511112  1.09066265  1.94488719
   0.57634452 -0.09057385  0.66435102 -1.09325131]
 [-0.09213224 -0.72925139  1.10081305  1.67185346  0.88874788 -0.89741586
   0.75551102  0.30251496 -0.42425082  1.657585  ]
 [-0.84478902  0.07091919 -0.34249028 -0.28192269 -1.32690943 -0.21564616
  -1.81694946  1.71213213  0.18090667  0.5780969 ]
 [ 1.69714827 -0.80672476 -1.51908949 -0.59372794  0.39728752 -0.31694606
  -0.33971875 -1.20478725  1.24848566 -0.38354047]]


In [33]:
y = x  - x.mean()
y = y / x.std()
print(y)

[[ 0.47321138 -0.92753693  1.56889388 -0.80058371 -1.05239472 -0.79784274
   1.61178121 -0.70015554 -0.57262385 -1.23508001]
 [-0.74245343  1.15711552 -0.17407542  0.59263887  1.40324156  0.30556754
   1.34623254 -0.26826472  1.15455893 -1.39312304]
 [ 0.10049585 -1.18715311  1.55422094  1.58605658  1.1715945  -0.96944236
   1.53771554  0.00176577  0.34892894 -0.09288085]
 [-0.51399659 -0.47447672 -0.1623091  -0.00911749 -1.37032202 -0.6636118
  -1.21158448  0.97009558  0.79678141 -0.60312422]
 [ 1.56132019 -1.25615521 -1.5616462  -0.26369305  0.60776579 -0.70905325
   0.36719601 -1.03366833  1.58685325 -1.05766289]]


**2.3.6.** Calule el capital final de invertir 500€ mensuales durante 10 años, a un interés anual del 10%

In [29]:
import numpy_financial as npf

In [30]:
npf.fv(rate = 0.1/12, nper = 10*12, pmt = 500, pv = 0)

-102422.48945173463